apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
    name: springboot-run
spec:
    pipelineRef:
        name: springboot-pipeline
    params:
        - name: GIT_URL
          value: https://github.com/anil-bijlwan/springboot-discount-api.git
        - name: IMAGE_NAME
          value: image-registry.openshift-image-registry.svc:5000/discount-api/modern-discount-api:latest
        - name: CONTEXT_DIR
          value: ./springboot-discount-api
    workspaces:
        - name: shared-workspace
          volumeClaimTemplate:
              metadata:
                  name: shared-pvc
              spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                      requests:
                          storage: 1Gi
        - name: maven-settings
          emptyDir: {}